version: '3'

services:

  mysql-service:
    image: mysql
    command:  --default-authentication-plugin=mysql_native_password --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: mysql-service
    volumes:
      - mysql-data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    restart: always
    networks:
      - service-net

  pma-service:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql-service
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql-service
    ports:
      - 8080:80
    restart: always
    depends_on:
      - mysql-service
    networks:
      - service-net

  rabbitmq-service:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq-service
      RABBITMQ_DEFAULT_PASS: rabbitmq-service
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    restart: always
    ports:
      - 5672:5672
    networks:
      - service-net

  redis-service:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: always
    networks:
      - service-net

volumes:
  mysql-data:
  rabbitmq-data:
  redis-data:

networks:
  service-net:
    driver: bridge
  